language: cpp

install:
 - sudo apt-get install -y gcc-multilib
 - sudo apt-get install -y g++-multilib
  
compiler:
 - clang
 - gcc

script:
 - mkdir _build
 - cd _build
 - cmake .. -DCMAKE_CXX_FLAGS="-m32" -DCMAKE_C_FLAGS="-m32"
 - make
 - cd bin
 - ./utee-runner ./libcommon.tests.so ./libcollector.tests.so ./libpatcher.tests.so
